apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jerney-gitops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/olayinka789/Jerney.git'
    targetRevision: main
    path: k8s-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jerney
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
