apiVersion: v1
kind: Secret
metadata:
  name: jerney-db-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: jerney
type: Opaque
data:
  POSTGRES_USER: {{ .Values.database.secret.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.database.secret.POSTGRES_PASSWORD }}
  POSTGRES_DB: {{ .Values.database.secret.POSTGRES_DB }}
